# Generated by Django 6.0 on 2026-01-08 15:23

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoStats',
            fields=[
                ('_id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('measurement_date', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Ручне введення'), ('auto', 'Автоматично (CGM)')], default='manual', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measurement_date'],
            },
        ),
    ]
