# Generated by Django 6.0 on 2026-01-15 22:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_glucostats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glucostats',
            name='notes',
        ),
        migrations.AddField(
            model_name='glucostats',
            name='context',
            field=models.CharField(choices=[('normal', 'Звичайний стан'), ('post_meal', 'Після їжі'), ('post_meds', 'Після ліків'), ('post_exercise', 'Після активності')], default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('activity_type', models.CharField(max_length=50)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('meal_type', models.CharField(max_length=50)),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(15)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('medicine_name', models.CharField(max_length=50)),
                ('dosage', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
    ]
