# Generated by Django 5.2.8 on 2025-12-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_customuser_diabetes_customuser_medic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='diabetes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hospital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='medic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
