# Generated by Django 6.0 on 2026-01-15 22:19

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0003_remove_glucostats_notes_glucostats_context_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mealevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medicationevent',
            name='id',
        ),
        migrations.AddField(
            model_name='activityevent',
            name='_id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mealevent',
            name='_id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='medicationevent',
            name='_id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
    ]
