# Generated by Django 6.0 on 2026-01-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0004_remove_activityevent_id_remove_mealevent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='diabetes',
            field=models.CharField(choices=[('type1', 'перший'), ('type2', 'другий')], default='type1', max_length=20),
        ),
    ]
