# Generated by Django 6.0 on 2026-01-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0005_alter_customuser_diabetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
